import turtle

turtle.bgcolor("black")
turtle.title("SASS")
turtle.pencolor("cyan")
turtle.width(3)

turtle.speed(30)

#for project name
turtle.color("black","cyan")
turtle.backward(600)
turtle.left(90)
turtle.forward(300)
turtle.right(90)
turtle.color("cyan")
turtle.forward(160)
turtle.backward(160)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(160)
turtle.backward(160)
turtle.left(180)
turtle.color("black","cyan")
turtle.forward(20)
turtle.left(90)
turtle.color("cyan")
turtle.forward(160)
turtle.right(90)
turtle.forward(110)
turtle.right(90)
turtle.forward(160)
turtle.backward(80)
turtle.right(90)
turtle.forward(110)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.color("black","cyan")
turtle.forward(130)
turtle.color("cyan")
turtle.forward(160)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(160)
turtle.color("black","cyan")
turtle.forward(20)
turtle.right(90)
turtle.color("black","cyan")
turtle.forward(160)
turtle.left(90)
turtle.color("cyan")
turtle.forward(160)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(160)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(160)
turtle.color("black","cyan")
turtle.forward(40)
turtle.color("cyan")
turtle.forward(90)
turtle.backward(90)
turtle.right(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(90)
turtle.backward(90)
turtle.color("black","cyan")
turtle.backward(20)
turtle.right(90)
turtle.color("cyan")
turtle.forward(80)
turtle.backward(40)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(40)
turtle.backward(80)
turtle.right(90)
turtle.color("black","cyan")
turtle.forward(20)
turtle.color("cyan")
turtle.forward(60)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(60)
turtle.color('black',"cyan")
turtle.forward(20)
turtle.left(90)
turtle.color("cyan")
turtle.forward(80)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(50)
turtle.backward(50)
turtle.left(90)




turtle.done()




